### ISSUE TITLE
Passing release libraries even compiling in debug mode

### ISSUE THREAD

**Issue by softwarejimenez** [rticommunity/rticonnextdds-examples#371]
### Information

- **RTI Product**: RTI Connext DDS PRO
- **Version**: 6.0.1
- **Operating system**: Linux 
- **Compiler**: x64Linuxegcc5.4.0
- **Additional information**: Debug

### What is the current behavior?
I want to reproduce the DDS code. However, it is using the release libraries even asking for the debug one.

### Steps to reproduce the issue
```
cd rticonnextdds-examples/examples/connext_dds/waitsets/c
mkdir build;cd build
cmake .. -DCONNEXTDDS_DIR=/home/ajimenez/rti_connext_dds/6.1.0/rti_connext_dds-6.1.0 -DCMAKE_BUILD_TYPE=DEBUG
cmake --build . --config debug -- VERBOSE=1
cgdb waitsets_publisher
```
![image](https://user-images.githubusercontent.com/5960625/111646564-0cbda780-8802-11eb-943a-7e642edc56c4.png)
If I try to step in the function `DDS_DomainParticipant_create_publisher`, it just continues. 

### What is the expected behavior?
I would expect that gdb tries to enter into `DDS_DomainParticipant_create_publisher`.

The reason is that it is compiled using the release libraries, however, I asked for the debug one. 
```
/usr/bin/cc -g   CMakeFiles/waitsets_subscriber_c.dir/waitsets_subscriber.c.o CMakeFiles/waitsets_C_obj.dir/src/waitsets.c.o CMakeFiles/waitsets_C_obj.dir/src/waitsetsPlugin.c.o CMakeFiles/waitsets_C_obj.dir/src/waitsetsSupport.c.o  -o waitsets_subscriber /home/ajimenez/rti_connext_dds/6.1.0/rti_connext_dds-6.1.0/lib/x64Linux3gcc5.4.0/libnddscz.a /home/ajimenez/rti_connext_dds/6.1.0/rti_connext_dds-6.1.0/lib/x64Linux3gcc5.4.0/libnddscorez.a -ldl -lm -lpthread -lrt
```
As you can see it is passing the release libraries:
- `rti_connext_dds-6.1.0/lib/x64Linux3gcc5.4.0/libnddscorez.a`
- `rti_connext_dds-6.1.0/lib/x64Linux3gcc5.4.0/libnddscz.a`

### Suggested solutions

After reviewing with Luis, we suggested me to use `-DCONNEXTDDS_IMPORTED_TARGETS_DEBUG=ON` and it worked.
I would say, `CONNEXTDDS_IMPORTED_TARGETS_DEBUG` should be set to true if the user wants to build in debug mode.

**Comment by iblancasa** [comment]
This is not a good idea because when a customer sets the build system in debug mode, wants to debug their application, not the ConnextDDS libraries. In the past, this  was a problem for different customers even for internal usage (during the creation of Routing Service Adapters, for instance). Forcing the user to link against our debug libraries is not a good idea.

By default, all the Find Package CMake scripts provide the release libraries because its what you, as final user, want to use.

So, to avoid the issues described before and to make the system flexible enough to link against the debug libraries, we added the `CONNEXTDDS_IMPORTED_TARGETS_DEBUG` CMake option.
